apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: some
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some
  template:
    metadata:
      labels:
        app: some
    spec:
      containers:
        - name: cnt
          image: terezabisharyan/kubia:72536b10618e046f166f612ff47b7cd309676b04
          ports:
            - containerPort: 8080
